/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { AxiosResponse } from "axios";
import { Expose, Type } from "class-transformer";

export class RedirectionDetails extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "failureMethod" })
    failureMethod?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "failureURL" })
    failureURL?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "redirectionRequired" })
    redirectionRequired?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "successMethod" })
    successMethod?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "successURL" })
    successURL?: string;
}

export class GenerateWebviewRequestBody extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "merchantId" })
    merchantId?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "partnerReferenceNo" })
    partnerReferenceNo?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "redirectionDetails" })
    @Type(() => RedirectionDetails)
    redirectionDetails?: RedirectionDetails;

    @SpeakeasyMetadata()
    @Expose({ name: "registrationToken" })
    registrationToken?: string;
}

export class GenerateWebviewRequest extends SpeakeasyBase {
    @SpeakeasyMetadata({ data: "header, style=simple;explode=false;name=CHANNEL-ID" })
    channelId?: string;

    @SpeakeasyMetadata({ data: "request, media_type=application/json" })
    requestBody?: GenerateWebviewRequestBody;

    @SpeakeasyMetadata({ data: "header, style=simple;explode=false;name=X-CLIENT-KEY" })
    xClientKey?: string;

    @SpeakeasyMetadata({ data: "header, style=simple;explode=false;name=X-EXTERNAL-ID" })
    xExternalId?: string;

    @SpeakeasyMetadata({ data: "header, style=simple;explode=false;name=X-Signature" })
    xSignature?: string;

    @SpeakeasyMetadata({ data: "header, style=simple;explode=false;name=X-Timestamp" })
    xTimestamp?: string;
}

export class GenerateWebviewResponse extends SpeakeasyBase {
    /**
     * HTTP response content type for this operation
     */
    @SpeakeasyMetadata()
    contentType: string;

    /**
     * HTTP response status code for this operation
     */
    @SpeakeasyMetadata()
    statusCode: number;

    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    @SpeakeasyMetadata()
    rawResponse?: AxiosResponse;
}
